# Generated by Django 5.2 on 2025-07-16 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliothecaire', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='annee',
            field=models.PositiveIntegerField(default=2020),
            preserve_default=False,
        ),
    ]
